# Starter pipeline

trigger:
- main

pool:
  # Estoy usando mi pool "defaul" porque estoy utilizando un agente autohospedado, porque la version gratuita no cuenta con agentes hospedados gratis
  name: Default
  
  # Para ejecutarlo en un agente hospedado se realizaria con el siguiente comando:
  # vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet
    
- script: |
    sudo apt-get update
    sudo apt-get install -y python3 python3-pip unzip
    if [ $? -ne 0 ]; then
        echo "Error: Failed to install dependencies"
        exit 1
    fi
    python3 -m pip install reflex
    if [ $? -ne 0 ]; then
        echo "Error: Failed to install reflex"
        exit 1
    fi
  displayName: 'Installing Dependencies'

- script: |
    git clone $(HTTPSRespository) || { echo "Error: Failed to clone repository"; exit 1; }
    cd MiguelDev/linkBio/ || { echo "Error: Failed to change directory to repository"; exit 1; }
    sh ./build.sh || { echo "Error: Build failed"; exit 1; }
  displayName: 'Cloning and building the application'