# Starter pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y python3 python3-pip python3.10-venv unzip
    if [ $? -ne 0 ]; then
        echo "Error: Failed to install dependencies"
        exit 1
    fi
    python3 -m pip install reflex
    if [ $? -ne 0 ]; then
        echo "Error: Failed to install reflex"
        exit 1
    fi
  displayName: 'Installing Dependencies'

- script: |
    git clone https://github.com/MiguelRodriguez11/MiguelDev.git || { echo "Error: Failed to clone repository"; exit 1; }
    cd MiguelDev/linkBio/ || { echo "Error: Failed to change directory to repository"; exit 1; }
    sh ./build.sh || { echo "Error: Build failed"; exit 1; }
  displayName: 'Cloning and building the application'